blank_issues_enabled: false
contact_links:
  - name: Discord
    url: https://discord.gg/SwUPVENQsd
    about: "**Please do not use Discord to file bug reports or make suggestions.** If you are having any minor issues or need help with the plugin, you can come ask us on our Discord server."
