# | =================================================== |
# |      Thank you for downloading and trying out       |
# |                       Quests                        |
# |      https://www.spigotmc.org/resources/23696/      |
# |         https://github.com/LMBishop/Quests/         |
# |                                                     |
# |                         =x=                         |
# |                                                     |
# |              Trying to add new quests?              |
# |                                                     |
# |                 Go to the 'quests'                  |
# |               subdirectory to edit the              |
# |                        quests                       |
# |                                                     |
# |                 The example quests                  |
# |              are commented to help you              |
# |             learn how to use the plugin             |
# |                                                     |
# |                         =x=                         |
# |                                                     |
# |              Have Discord & need help?              |
# |       Head to the GitHub page and click on the      |
# |           Discord link, or create an issue          |
# | =================================================== |

# Trying to add new categories? This has been moved to categories.yml

# The items listed below are placeholder items for quests which the player cannot start.
# You should change these for 1.8
gui:
  back-button:
    name: "&cReturn"
    lore:
    - "&7Return to the categories menu."
    type: "ARROW"
  page-prev:
    name: "&7Previous Page"
    lore:
    - "&7Switch the page to page &c{prevpage}."
    type: "FEATHER"
  page-next:
    name: "&7Next Page"
    lore:
    - "&7Switch the page to page &c{nextpage}."
    type: "FEATHER"
  page-desc:
    name: "&7Page &c{page}"
    lore:
    - "&7You are currently viewing page &c{page}."
    type: "PAPER"
  quest-locked-display:
    name: "&c&lQuest Locked"
    lore:
    - "&7You have not completed the requirements"
    - "&7for this quest (&c{quest}&7)."
    - ""
    - "&7Requires: &c{requirements}"
    - "&7to be completed to unlock."
    type: "RED_STAINED_GLASS_PANE"
  quest-permission-display:
    name: "&6&lNo Permission"
    lore:
    - "&7You do not have permission for this"
    - "&7quest (&6{quest}&7)."
    type: "BROWN_STAINED_GLASS_PANE"
  quest-cooldown-display:
    name: "&e&lQuest On Cooldown"
    lore:
    - "&7You have recently completed this quest"
    - "&7(&e{quest}&7) and you must"
    - "&7wait another &e{time} &7to unlock again."
    type: "ORANGE_STAINED_GLASS_PANE"
  quest-completed-display:
    name: "&a&lQuest Complete"
    lore:
    - "&7You have completed this quest"
    - "&7(&a{quest}&7) and cannot."
    - "&7repeat it."
    type: "GREEN_STAINED_GLASS_PANE"
  no-started-quests:
    name: "&c&lNo Started Quests"
    lore:
    - "&7Go start some!"
    type: "FEATHER"
  quest-cancel-yes:
    name: "&a&lConfirm Cancel"
    lore:
    - "&7Confirm you wish to cancel"
    - "&7this quest and lose all"
    - "&7progress."
    type: "GREEN_STAINED_GLASS_PANE"
  quest-cancel-no:
    name: "&c&lAbort Cancel"
    lore:
    - "&7Return to the quest menu."
    type: "RED_STAINED_GLASS_PANE"
  quest-cancel-background:
    type: "GRAY_STAINED_GLASS_PANE"

# Here you can add custom items to the quest menu
# Categories & quests will fill empty slots
#custom-elements:
#  "categories": # apply to the categories menu (the main menu by default)
#    0:   # <--- slot 1, note the slots start from 0! so 0 = slot 1 in this case
#      display:
#        name: "&cExample Custom Item (slot 1)"
#        lore:
#          - "&7This is a custom item which can be added"
#          - "&7to your menus. This is purely cosmetic."
#          - ""
#          - "&7Two empty slots should follow."
#        type: "DIAMOND_BLOCK"
#    1:   # <--- start from slot 2
#      spacer: true # empty slot in GUI
#      repeat: 2 # repeats for 2 slots
#    3:   # <--- start from slot 4
#      display:
#        name: "&cExample Custom Item (slots 4 - 7)"
#        lore:
#          - "&7This is a custom item which can be added"
#          - "&7to your menus, but in slot 4 and repeated"
#          - "&73 times."
#          - "&7"
#          - "&7This will come after 2 empty slots."
#          - "&7"
#          - "&7This is purely cosmetic."
#        type: "NETHERRACK"
#      repeat: 3 # repeats for 3 more slots
#  "c:examples": # apply to the category "examples"
#    0:
#      display:
#        name: "&cExample Custom Item (slot 1)"
#        lore:
#          - "&7This is a custom item which can be added"
#          - "&7to your menus. This is purely cosmetic."
#        type: "EMERALD_BLOCK"
#  "quests": # apply to the general quests menu IF categories are disabled
#    0:
#      display:
#        name: "&cExample Custom Item (slot 1)"
#        lore:
#          - "&7This is a custom item which can be added"
#          - "&7to your menus. This is purely cosmetic."
#        type: "EMERALD_BLOCK"

options:
  # If categories are disabled, quests will be put into one big gui.
  categories-enabled: true
  # If true, the gui size will automatically change based on the amount of quests inside it.
  trim-gui-size: true
  # Enable/disable titles
  titles-enabled: true
  # Allow players to have multiple active quests.
  # You can set the default number of quests using the 'default' rank below.
  # To grant different quest limits to different people, you can define a 'quest-rank'
  # Create the 'quest-rank' below, and give the matching permission: quests.limit.<quest-rank>
  quest-limit:
    default: 2
    #vip: 5
    #staff: 10
  # Allow players to cancel a quest (you may want to remove the cancel instructions in the global item lore)
  allow-quest-cancel: true
  # Allow players to track a quest (you may want to remove the tracking instructions in the global item lore)
  allow-quest-track: true
  # Task type exclusions - include task IDs in this list which you don't want registering
  task-type-exclusions: []
  # Titles for the GUIs
  guinames:
    quests-category: "Quests Categories"
    quests-menu: "Quests"
    quests-started-menu: "Started Quests"
    daily-quests: "Daily Quests"
    quest-cancel: "Cancel Quest"
  # See https://github.com/LMBishop/Quests/wiki/Basic-Options#sounds
  sounds:
    quest-start: "ENTITY_PLAYER_LEVELUP:2:3"
    quest-cancel: "UI_TOAST_OUT:2:3"
    quest-complete: "UI_TOAST_CHALLENGE_COMPLETE:1.25:3"
    gui:
      open: "ITEM_BOOK_PAGE_TURN:1:3"
      interact: ""
  # Hide locked quests, quests on cooldown and completed (but not repeatable) quests
  gui-hide-locked: false
  # Confirm quest cancellation with a separate menu
  gui-confirm-cancel: true
  # Hide quests which a player cannot start due to permissions.
  gui-hide-quests-nopermission: false
  # Hide categories which a player cannot open due to permissions.
  gui-hide-categories-nopermission: false
  # Replace placeholders from PlaceholderAPI in Quests GUI items
  gui-use-placeholderapi: false
  # Truncate quest requirements when there are multiple requirements to prevent enormous display items
  gui-truncate-requirements: true
  # Set the action buttons for the GUI
  gui-actions:
    start-quest: "LEFT"
    track-quest: "MIDDLE"
    cancel-quest: "RIGHT"
  # Make it so players do not have to start quest themselves
  quest-autostart: false
  # Automatically track quests on start, and stop tracking on completion
  quest-autotrack: true
  # How much quests should log, 0 = errors only, 1 = warnings, 2 = info, 3 = debug
  verbose-logging-level: 2
  # Record Quests log history for /q a debug
  record-log-history: true
  # Replace placeholders from PlaceholderAPI in rewards, rewardstrings and start strings
  quests-use-placeholderapi: false
  # Verify quests exist when a player's data is loaded - inconsistencies may arise when
  # players progress on specific quests and those quests are later removed. The problem is that their progress
  # is still kept in the quest progress file, which may lead to issues such as players reaching a quest started
  # limit when the quests they had active no longer exist - having this option enabled prevents
  # non-existent quests from being loaded
  verify-quest-exists-on-load: true
  performance-tweaking: # The following are measured in server ticks, multiply SECONDS by 20 to get the number of ticks.
    quest-queue-executor-interval: 1      # how frequently Quests should execute the next check in the completion queue (def=1 - 0.05s) - increase this value if you are struggling with performance
    quest-autosave-interval: 12000        # how frequently online players data will be autosaved (def=12000 - 10 minutes)
  tab-completion:
    enabled: true
  error-checking:
    # Allow quests to be loaded if they contain errors
    # This may lead to errors in the console!
    override-errors: false
  # How much time (in seconds) that plugin will cache placeholders
  placeholder-cache-time: 10
  # Whether or not the global task configuration will override per-task configuration settings
  global-task-configuration-override: false
  # Whether or not the global display configuration will override per-quest display settins
  global-quest-display-configuration-override: false
  # Storage options - please see the following: https://github.com/LMBishop/Quests/wiki/Storage-Providers
  storage:
    # Either 'yaml' (flatfile) or 'mysql' (network)
    # Please read the following before using MySQL https://github.com/LMBishop/Quests/wiki/Storage-Providers#network
    provider: "yaml"
    # See: https://github.com/LMBishop/Quests/wiki/Storage-Providers#Data-synchronisiation
    #      https://github.com/LMBishop/Quests/issues/180
    synchronisation:
      delay-loading: 0 # (ticks)
    # The following is only applicable for database storage providers (e.g. mysql)
    database-settings:
      network:
        # The name of the database. This database should already exist!
        database: "minecraft"
        username: "root"
        password: ""
        # Address should be in the format ip:port (just like the game itself)
        address: "localhost:3306"
      # This plugin uses 'HikariCP' for connection management, the pooling configuration can be changed here
      connection-pool-settings:
        # The maximum number of connections to keep open with the database (def=8)
        maximum-pool-size: 8
        # The minimum number of connections to keep open with the database (def=8)
        minimum-idle: 8
        # The maximum time (in milliseconds) to keep a single connection open (def=1800000 - 30 min)
        maximum-lifetime: 1800000
        # The time (in milliseconds) the plugin will wait for a response by the database (def=500)
        connection-timeout: 5000
      # The prefix each table will use
      table-prefix: "quests_"


quest-mode:
  mode: "NORMAL" # More modes are a work in progress

# The global task configuration will apply to the config of each task of a specified type in each quest.
# In the example below, every task with a type of "inventory" will have the config option "update-progress"
# set to true. This is useful if you do not want to go through each quest if you want to update the configuration
# for every task of a specific type.
#
# You must uncomment all below lines for the example to have any effect
# vvvvvvvvvvvvvvvvvvvvvvvvv
#global-task-configuration:
#  types:
#    inventory:
#      update-progress: true

global-quest-display:
  lore:
#    append-normal:
#      - "..."
    append-not-started:
      - ""
      - "&eLeft Click &7to start this quest."
    append-started:
      - ""
      - "&aYou have started this quest."
      - "&eMiddle Click &7to track this quest."
      - "&eRight Click &7to cancel this quest."
    append-tracked:
      - ""
      - "&aYou are &etracking &athis quest."
      - "&eMiddle Click &7to stop tracking this quest."
      - "&eRight Click &7to cancel this quest."

# Macros for faster quests configuration without having to repeat
# yourself.
# See wiki for more information.
global-macros:
  bar: "&6---&7---&6---"

# Configure titles
titles:
  quest-start:
    title: "&cQuest Started"
    subtitle: "&7{quest}"
  quest-complete:
    title: "&cQuest Complete"
    subtitle: "&7{quest}"

# Configure messages
messages:
  time-format: "{hours}h {minutes}m"
  quest-start: "&7Quest &c{quest} &7started!"
  quest-complete: "&7Quest &c{quest} &7completed!"
  quest-cancel: "&7Quest &c{quest} &7cancelled!"
  quest-expire: "&7Quest &c{quest} &7has expired."
  quest-track: "&7Tracking quest &c{quest}&7."
  quest-track-stop: "&7No longer tracking quest &c{quest}&7."
  quest-random-none: "&cYou have no quests which you can start."
  quest-start-limit: "&7Players are limited to &c{limit} &7started quests at a time."
  quest-start-disabled: "&7You cannot repeat this quest."
  quest-start-locked: "&7You have not unlocked this quest yet."
  quest-start-cooldown: "&7You have recently completed this quest. You have to wait &c{time} &7until you are able to restart it."
  quest-start-started: "&7You have already started this quest."
  quest-start-permission: "&7You do not have permission to start this quest."
  quest-category-permission: "&7You do not have permission to view this category."
  quest-category-quest-permission: "&7You do not have permission to start this quest since it is in a category you do not have permission to view."
  quest-cancel-notstarted: "&7You have not started this quest."
  quest-cancel-notcancellable: "&7You cannot cancel this quest."
  quest-updater: "&cQuests > &7A new version &c{newver} &7was found on Spigot (your version: &c{oldver}&7). Please update me! <3 - Link: {link}"
  command-data-not-loaded: "&4Your quests progress file has not been loaded; you cannot use quests. If this issue persists, contact an admin."
  command-sub-doesntexist: "&7The specified subcommand '&c{sub}' &7does not exist."
  command-quest-cancel-specify: "&7You must specify a quest to cancel."
  command-quest-start-doesntexist: "&7The specified quest '&c{quest}&7' does not exist."
  command-quest-general-doesntexist: "&7The specified quest '&c{quest}&7' does not exist."
  command-category-open-disabled: "&7Categories are disabled."
  command-category-open-doesntexist: "&7The specified category '&c{category}&7' does not exist."
  command-quest-admin-playernotfound: "&7Player '&c{player}&7' could not be found."
  command-quest-openquests-admin-success: "&7Opened Quest GUI for player &c{player}&7."
  command-quest-openstarted-admin-success: "&7Opened started Quest GUI for player &c{player}&7."
  command-quest-opencategory-admin-success: "&7Opened category &c{category} &7for player &c{player}&7."
  command-taskview-admin-fail: "&7Task type '&c{task}&7' does not exist."
  beta-reminder: "&cQuests > &7Reminder: you are currently using a &cbeta &7version of Quests. Please send bug reports to https://github.com/LMBishop/Quests/issues and check for updates regularly using &c/quests admin update&7!"
  command-quest-admin-loaddata: "&7Quest data for '&c{player}&7' is being loaded."
  command-quest-admin-nodata: "&7No data could be found for player &c{player}&7."
  command-quest-admin-fullreset: "&7Data for player &c{player}&7 has been fully reset."
  command-quest-admin-start-faillocked: "&7Quest '&c{quest}&7' could not be started for player &c{player}&7. They have not yet unlocked it."
  command-quest-admin-start-failcooldown: "&7Quest '&c{quest}&7' could not be started for player &c{player}&7. It is still on cooldown for them."
  command-quest-admin-start-failcomplete: "&7Quest '&c{quest}&7' could not be started for player &c{player}&7. They have already completed it."
  command-quest-admin-start-faillimit: "&7Quest '&c{quest}&7' could not be started for player &c{player}&7. They have reached their quest start limit."
  command-quest-admin-start-failstarted: "&7Quest '&c{quest}&7' could not be started for player &c{player}&7. It is already started."
  command-quest-admin-start-failpermission: "&7Quest '&c{quest}&7' could not be started for player &c{player}&7. They do not have permission."
  command-quest-admin-start-failcategorypermission: "&7Quest '&c{quest}&7' could not be started for player &c{player}&7. They do not have permission for the category which the quest is in."
  command-quest-admin-start-failother: "&7Quest '&c{quest}&7' could not be started for player &c{player}&7."
  command-quest-admin-start-success: "&7Quest &c{quest} &7started for player &c{player}&7."
  command-quest-admin-category-permission: "&7Category &c{category} &7 could not be opened for player &c{player}&7. They do not have permission to view it."
  command-quest-admin-complete-success: "&7Quest &c{quest} &7completed for player &c{player}&7."
  command-quest-admin-reset-success: "&7Successfully reset quest '&c{quest}&7' for player &c{player}&7."
  command-quest-admin-random-none: "&7Player &c{player}&7 has no quests which they can start."
  command-quest-admin-random-success: "&7Successfully started random quest '&c{quest}&7' for player &c{player}&7."
  command-quest-admin-random-category-none: "&7Player &c{player}&7 has no quests in category '&c{category}&7' which they can start."
  command-quest-admin-random-category-success: "&7Successfully started random quest '&c{quest}&7' from category '&c{category}&7' for player &c{player}&7."
  ui-placeholder-completed-true: "true"
  ui-placeholder-completed-false: "false"
  ui-placeholder-truncated: " +{amount} more"
  placeholderapi-true: "true"
  placeholderapi-false: "false"
  placeholderapi-no-tracked-quest: "No tracked quest"
  placeholderapi-data-not-loaded: "Data not loaded"
